Add USSD tests
glushkovds/php-smpp pull request #7
Opened 2020-11-28 06:59 UTC by Subb98

Close #6

2020-11-29 09:24 UTC, glushkovds requested changes

2020-11-29 09:24 UTC, glushkovds commented on src/Pdu/SmppUssd.php
> +class SmppUssd extends Sm
Please use shorter name: Ussd.  
I see you name it like SmppSms. This class will be deprecated and will be alias to Sms later. In 1.0 version it will be removed.

2020-11-29 09:24 UTC, glushkovds commented on src/Tests/ReadUSSDTest.php
> +            $this->assertEquals(SMPP::ESME_ROK, $pdu->status);
Add assertion of serviceType

2020-11-29 09:24 UTC, glushkovds commented on src/Tests/SendUSSDTest.php
> +<?php
If possible add USSD communication test:
1. receive USSD - subscriber service purchase request.
1. and send response USSD - please wait request status in SMS.

2020-11-29 09:24 UTC, glushkovds commented on src/Tests/SendUSSDTest.php
> +namespace PhpSmpp\Tests;
Also we need patch Readme.md - how to send and receive USSD.

2020-11-30 09:15 UTC, Subb98 commented on README.md
> +$service = new \PhpSmpp\Service\Listener([], ['smschost.net'], 'login', 'pass');
Oops! The order of parameters is broken. It will be fixed..

2020-12-03 09:11 UTC, glushkovds requested changes

2020-12-03 09:11 UTC, glushkovds commented on README.md
> +    if ($pdu instanceof \PhpSmpp\Pdu\Ussd && $pdu->serviceType === \PhpSmpp\SMPP::SERVICE_TYPE_USSD) {
Need to remove unnecessary second condition

2020-12-03 09:11 UTC, glushkovds commented on README.md
> +$service->listenOnce(function (\PhpSmpp\Pdu\Pdu $pdu) {
listen instead of listenOnce. listenOnce only for debug issues.

2020-12-03 09:11 UTC, glushkovds commented on README.md
> +        echo 'not ussd';
Not necessary else statement

2020-12-05 11:48 UTC, Subb98 commented on src/Tests/SendUSSDTest.php
> +<?php
I updated the src/Tests/ReadUSSDTest class by adding the send USSD request function to the callback

2020-12-06 14:12 UTC, merged